Implement choose to compare
GymTecProject/gym-tec-app pull request #28
Opened 2023-11-02 23:07 UTC by earlac

Adding the dropdown list where previous measures must be added to be loaded to measures landing page, so it can be compared

@JGamboaB to implement call to db

2023-11-02 23:40 UTC, danielcornejo14 requested changes

2023-11-02 23:40 UTC, danielcornejo14 commented on .vscode/launch.json
meter esto en .gitignore

2023-11-02 23:40 UTC, danielcornejo14 commented on lib/pages/user/profile/measurement.dart
> +class MyCollapsibleList extends StatefulWidget {
falta constructor constante

2023-11-02 23:40 UTC, danielcornejo14 commented on lib/pages/user/profile/measurement.dart
> +class Item {
Usar un nombre mas descriptivo para la clase y sus metodos

2023-11-02 23:40 UTC, danielcornejo14 commented on lib/pages/user/profile/measurement.dart
> +  Widget _buildPanel() {
mover este metodo arriba de build para congruencia (Build deberia de ser el ultimo metodo de la clase)

2023-11-02 23:40 UTC, danielcornejo14 commented on lib/pages/user/profile/measurement.dart
> +  const MeasurementPage({Key? key}) : super(key: key);
usar `const MeasurementPage({super.key})` para tener congruencia con el resto del app

2023-11-02 23:40 UTC, danielcornejo14 commented on lib/pages/user/profile/measurement.dart
separar clases en diferentes archivos, no tener más de un widget en un solo archivo

estructura:
- components
    - profile
        - item.dart (con un nombre más descriptivo) 
- profile:
    - measurement.dart
    - profile.dart

2023-11-04 20:21 UTC, earlac commented on .vscode/launch.json
Change implemented. Resolving

2023-11-04 20:21 UTC, earlac commented on lib/pages/user/profile/measurement.dart
> +class Item {
Change implemented. Resolved

2023-11-04 20:22 UTC, earlac commented on lib/pages/user/profile/measurement.dart
> +class MyCollapsibleList extends StatefulWidget {
Changes implemented. Resolving

2023-11-04 20:22 UTC, earlac commented on lib/pages/user/profile/measurement.dart
> +  Widget _buildPanel() {
Changes implemented. Resolving

2023-11-04 20:22 UTC, earlac commented on lib/pages/user/profile/measurement.dart
> +  const MeasurementPage({Key? key}) : super(key: key);
Changes implemented. Resolving

2023-11-05 02:29 UTC, danielcornejo14 requested changes

2023-11-05 02:29 UTC, danielcornejo14 commented on lib/components/profile/measurement_Item.dart
Si esto es un tipo de dato entonces debe de ir a la capeta /models
(Basicamente si es una clase que no crea ningun widget y solo contiene datos entonces en un modelo de datos)

2023-11-05 02:29 UTC, danielcornejo14 commented on lib/pages/user/profile/measurement.dart
>  class MeasurementPage extends StatefulWidget {
Si esto es un dialog o algo debe estar en su propia carpeta /pages/user/profile/profile_dialogs/measurement_page.dart

Solo debe de haber un metodo `build` por archivo

2023-11-14 15:43 UTC, danielcornejo14 approved these changes

2023-11-14 15:43 UTC, merged